services:
  php:
    build:
      context: ./docker/php
    container_name: php
    restart: unless-stopped
    networks:
      - proxy
    expose:
      - "9000"
    volumes:
      - .:/home/app:cached
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    networks:
      - proxy
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql:rw
  nginx:
    build: ./docker/nginx
    container_name: nginx
    restart: unless-stopped
    networks:
      - proxy
    expose:
      - "80"
      - "443"
    depends_on:
      - php
    volumes:
      - .:/home/app:cached
      - ./docker/nginx/logs:/var/log/nginx:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/snippets:/etc/nginx/snippets:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro

volumes:
  mysql_data:

networks:
  proxy:
    external: true

