services:
  fpm:
    build:
      context: ./docker/php
    container_name: fpm
    expose:
      - "9000"
    volumes:
      - ${APP_PATH}:/home/app
  cli:
    build:
      context: ./docker/php
      dockerfile: Dockerfile.cli
    container_name: cli
    ports:
      - "8000:8000"
    volumes:
      - ${APP_PATH}:/home/app
  mysql:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:rw
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:3306"
  nginx:
    build: ./docker/nginx
    container_name: nginx
    restart: always
    depends_on:
      - fpm
    volumes:
      - ${APP_PATH}:/home/app
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${CERT}:/etc/nginx/ssl/localhost-cert.pem:ro
      - ${CERT_KEY}:/etc/nginx/ssl/localhost-key.pem:ro
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"

